name=input("Enter your Name:")
age=int(input("Enter your Age:"))
college=input("Enter your College:")
branch=input("Enter your Branch:")
year=int(input("Enter your Year:"))
cgpa=float(input("Enter your CGPA:"))

print("###STUDENT INFORMATION###")
print("NAME:",name.upper())
print("AGE:",age)
print("COLLEGE:",college.title())
print("BRANCH:",branch.upper())
print("YEAR:",year)
print("CGPA:",cgpa)
print("###################")

print(f"your full name is {name} and you are studying in {college}in {year}year")