name=input("Enter your Name:")
age=int(input("Enter your Age:"))
college=input("Enter your College:")
branch=input("Enter your Branch:")
year=int(input("Enter your Year:"))
cgpa=float(input("Enter your CGPA:"))

print("###STUDENT INFORMATION###")
print("NAME:",name)
print("AGE:",age)
print("COLLEGE:",college)
print("BRANCH:",branch)
print("YEAR:",year)
print("CGPA:",cgpa)
print("###################")